version: '3.9'

services:
  rstudio:
    image: rocker/tidyverse:4.1.2
    volumes:
      - ${PWD}/workdir:/home/rstudio
      - site-library:/usr/local/lib/R/site-library
    ports:
      - 8787:8787
    environment:
      - DISABLE_AUTH=true

volumes:
  site-library: